# worflow Name
name : First Workflow
# trigger
on :
  push:
  workflow_dispatch:
jobs:
  Hello-job :
  #runner - guthub hosted
    runs-on : ubuntu-latest
    steps:
      - name: hello world
        run : echo "Hello world"
      - name : Even Name
        run : echo "Event Name :${{github.event_name}}" # Context Reference
        
  # second job
  echo-goodbye:
      needs : Hello-job
      runs-on : ubuntu-slim
      steps:
        - name: Say GoodBye
          run: echo "Goodbye!"
        # Multiple command
        - name : Multi-line bash
          run : |
            echo "This is"
            echo "Paul here"
            echo "script"

  #third job
  window-echo:
    if: github.event_name == 'Workflow_dispatch'
    runs-on: windows-lastest
    steps:
      - name : show OS
        shell : bash
        run : echo "The job is running"
      
      
