# worflow Name
name : First Workflow
# trigger
on :
  push:
  workflow_dispatch:
jobs:
  Hello-job :
  #runner - guthub hosted
    runs-on : ubuntu-latest
    steps:
      - name: hello world
        run : echo "Hello world"
