# worflow Name
name : First Workflow
# trigger
on :
  push:
  workflow_dispatch:
jobs:
  Hello-job :
  #runner - guthub hosted
    runs-on : ubuntu-latest
    steps:
      - name: hello world
        run : echo "Hello world"
      - name : Even Name
        run : echo "Event Name :${{github.event_name}}" # Context Reference
        #run: echo "Deploying to ${{ inputs.deploy_target }}"
        
  # second job
  echo-goodbye:
      needs : Hello-job
      runs-on : ubuntu-slim
      steps:
        - name: Say GoodBye
          run: echo "Goodbye!"
        # Multiple command
        - name : Multi-line bash
          run : |
            echo "Hello"
            echo "Paul Script"
            echo "Here attached"

  #third job
  window-echo:
    #if: github.event_name == 'Workflow_dispatch'
    if: ${{ github.event.requested_team.name == 'octo-team'}}
    runs-on: windows-lastest
    steps:
      - name : show OS
        shell : bash
        run : echo "The job is running"
      
      
